# docker-compose.yml
version: '3.8'

services:
  flowbot:
    build: .
    container_name: flowbot
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./logs:/app/logs
      - ./data:/app/data
    networks:
      - flowbot-network
    depends_on:
      - redis

  redis:
    image: redis:7-alpine
    container_name: flowbot-redis
    restart: unless-stopped
    command: redis-server --appendonly yes
    volumes:
      - redis-data:/data
    networks:
      - flowbot-network
    ports:
      - "6379:6379"

networks:
  flowbot-network:
    driver: bridge

volumes:
  redis-data:
